version: '3.8'

services:
  go_web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - data:/app/data
    ports:
      - "8080:8080"
    environment:
      - SENDGRID_API_KEY=your_key
      - SENDGRID_API_SENDER_EMAIL=your_email
      - SENDGRID_API_SENDER_NAME=your_name

volumes:
  data:
