basePath: /api
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for a BTC to UAH rate application.
  title: GSES2 BTC application API
  version: 1.0.0
paths:
  /rate:
    get:
      description: Get the current rate of BTC to UAH using any third-party service
        with public API
      produces:
      - application/json
      responses:
        "200":
          description: Successful operation
          schema:
            type: number
        "400":
          description: Invalid status value
          schema:
            type: string
      summary: Get current BTC to UAH rate
      tags:
      - rate
  /sendEmails:
    post:
      description: Send the current BTC to UAH rate to all subscribed emails
      produces:
      - application/json
      responses:
        "200":
          description: E-mails sent
          schema:
            type: string
      summary: Send email with BTC rate
      tags:
      - subscription
  /subscribe:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Add an email to the database if it does not exist already
      parameters:
      - description: Email to be subscribed
        in: formData
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: E-mail added
          schema:
            type: string
        "409":
          description: E-mail already exists in the database
          schema:
            type: string
      summary: Subscribe email to get BTC rate
      tags:
      - subscription
swagger: "2.0"
